import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Hero from '../components/HomePage/Hero'
import Ribon from '../components/HomePage/Ribon'
import Library from '../components/HomePage/Library'
import Live from '../components/HomePage/Live'
import WelcomeTab from '../components/HomePage/WelcomeTab'
import Footer from '../components/HomePage/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Stream Tv and Movies Live and Online | Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico.png" />
      </Head>

      <main className={styles.main}>
        <Hero></Hero>
        <Ribon></Ribon>
        <Library></Library>
        <Live></Live>
        <WelcomeTab></WelcomeTab>
        <Footer></Footer>
      </main>
        
    </div>
  )
}
